<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonlgn</name>
   <tag></tag>
   <elementGuidId>0bf03957-ad39-4b7f-89c6-d466d3b6e8d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;login-button&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;login-button&quot;]</value>
      <webElementGuid>5f3e8794-850f-4c81-bb6e-59deb32fcfd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
