<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_profile</name>
   <tag></tag>
   <elementGuidId>95e75d52-3f07-4e01-a068-5ce4de7bfb22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div/div[1]/div[1]/header/div/div/div[2]/button/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div/div[1]/div[1]/header/div/div/div[2]/button/div/span</value>
      <webElementGuid>83543958-96c8-42bb-b565-b082cc6d7db7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
