<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Buat_Grup_Payroll</name>
   <tag></tag>
   <elementGuidId>19d20039-39c9-44dd-92d9-112ec3d8c4dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;tabpanel-1&quot;]/div[1]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;tabpanel-1&quot;]/div[1]/div/button</value>
      <webElementGuid>c33cd2a8-7c1c-4dec-aeaf-4c1653f9448d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
