<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_Berita_Payroll</name>
   <tag></tag>
   <elementGuidId>1a5bed92-3a80-49ce-976e-2a32c4ae5337</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div[3]/div/form/div[1]/div/div[2]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>/html/body/div[2]/div[3]/div/form/div[1]/div/div[2]/div/div/input</value>
      <webElementGuid>ca6d8381-4ed1-4548-8120-e73cf2cdf050</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
