<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_Nomor_Rekening</name>
   <tag></tag>
   <elementGuidId>e84009a8-8ef1-487f-9213-04bc6134530a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;account&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;account&quot;]</value>
      <webElementGuid>9001693f-47e8-4a77-8bc5-a465261f247b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
