<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_Email</name>
   <tag></tag>
   <elementGuidId>b845c79d-8c85-40db-a6d8-17e2ad7e0a43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;email&quot;]</value>
      <webElementGuid>3f6fd15a-8e40-49bb-8c5f-4ad8b546683a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
