<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_Nama_Grup</name>
   <tag></tag>
   <elementGuidId>736f0663-ac29-4d85-9c13-10dd61403835</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div[3]/div/form/div[1]/div/div[1]/div[2]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>/html/body/div[2]/div[3]/div/form/div[1]/div/div[1]/div[2]/div/div/input</value>
      <webElementGuid>739cb6ec-64dc-4208-86ad-8aa49ecee15c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
