<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_Berita</name>
   <tag></tag>
   <elementGuidId>8d383a69-6b4d-4402-9dde-e58ab78dd244</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div[3]/div/form/div[1]/div/div[4]/div[3]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>/html/body/div[2]/div[3]/div/form/div[1]/div/div[4]/div[3]/div/div/input</value>
      <webElementGuid>003f3f3a-ac00-426d-a70d-68bc02095d90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
